[package]
name = "job_tracker_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4", features = ["derive"]} # CLI parsing
anyhow = "1" # ergonomic error handling
serde = {version = "1", features = ["derive"]}
serde_json = "1"