spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://samidmunir:QcOoejfyhScXyuPV@fitness-tracker-activit.barwpke.mongodb.net/?retryWrites=true&w=majority&appName=fitness-tracker-activity
      database: fitness-tracker-recommendation

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
